---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: k8s-volume-injector
  namespace: k8s-volume-injector
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-volume-injector
  namespace: k8s-volume-injector
spec:
  commonName: k8s-volume-injector.k8s-volume-injector.svc
  dnsNames:
  - k8s-volume-injector.k8s-volume-injector.svc.cluster.local
  - k8s-volume-injector.k8s-volume-injector.svc
  issuerRef:
    kind: Issuer
    name: k8s-volume-injector
  secretName: k8s-volume-injector-cert
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-volume-injector
  namespace: k8s-volume-injector
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/part-of: k8s-volume-injector
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-volume-injector
  namespace: k8s-volume-injector
  labels:
    app.kubernetes.io/part-of: k8s-volume-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: k8s-volume-injector
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: k8s-volume-injector
    spec:
      volumes:
      - name: certs
        secret:
          secretName: k8s-volume-injector-cert
      - name: config
        configMap:
          name: k8s-volume-injector-config
      containers:
      - name: k8s-volume-injector
        imagePullPolicy: Always
        image: "atorrescogollo/k8s-volume-injector:latest"
        ports:
        - name: https
          containerPort: 9443
        - name: http-metrics
          containerPort: 9000
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: config
          mountPath: /config
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /health
            port: https
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          requests:
            cpu: "0.3"
            memory: "0.5Gi"
          limits:
            cpu: "0.5"
            memory: 2Gi
        env:
        - name: "CONFIG_FILE"
          value: "/config/config.yaml"

